include:
  - project: 'iopsys/gitlab-ci-pipeline'
    file: '/static-code-analysis.yml'

stages:
    - static_code_analysis
    - unit_test
    - functional_test
    - api_test

variables:
  DEBUG: 'TRUE'
  SOURCE_FOLDER: "./src"
  RUN_CPPCHECK: "cppcheck --enable=all --error-exitcode=1 --suppress=missingIncludeSystem ${SOURCE_FOLDER}"

run_api_test:
    stage: api_test
    image: iopsys/code-analysis-dev
    allow_failure: false
    script:
        - "./gitlab-ci/install-dependencies.sh"
        - "./gitlab-ci/setup.sh"
        - "./gitlab-ci/functional-api-test.sh"

    artifacts:
        when: always
        reports:
            junit: ./report/*.xml
        paths:
            - api-test-coverage.xml
            - memory-report.xml
            - api-result.log
            - report/

run_unit_test:
    stage: unit_test
    image: iopsys/code-analysis-dev
    allow_failure: true
    script:
        - "./gitlab-ci/install-dependencies.sh"
        - "./gitlab-ci/setup.sh"
        - "./gitlab-ci/unit-test.sh"

    artifacts:
        when: always
        paths:
            - unit-test-coverage.html

run_functional_test:
    stage: functional_test
    image: iopsys/code-analysis-dev
    allow_failure: true
    script:
        - "./gitlab-ci/install-dependencies.sh"
        - "./gitlab-ci/setup.sh"
        - "./gitlab-ci/functional-test.sh"

    artifacts:
        when: always
        paths:
            - functional-test-coverage.html
